### ISSUE TITLE
python environment not setup correctly on fresh Debian 8 install

### ISSUE THREAD

**Issue by 2600box** [pyroscope/pimp-my-box#11]
I have a fresh Debian 8 install. 

Used pimp-my-box to install, but the default environment complains about "--no-error" is not a version and the default python environment is not loaded.

i removed the --no-error elements from pyenv.sh and now ever prompt says `pyenv-virtualenv: version `2.7.13' is not a virtualenv` which I haven't been able to resolve.

my hack workaround is to add PYTHONPATH to the `start` script

**Comment by pyroscope** [comment]
It's unclear where and when these errors occur.

Also, using the system Python (Jessie comes with a reasonably new version) as shown in the README will likely fix this, too.

**Comment by 2600box** [comment]
agreed. just wanted to bring it to your attention so that it may be looked at in the default ansible install.

**Comment by pyroscope** [comment]
Which still leaves us with "no clue when and where this occurs".

**Comment by pyroscope** [comment]
No further feedback.

**Comment by 2600box** [comment]
Hey. I have been looking at this again because it has been annoying me. It seems to be a syntax issue with https://github.com/pyroscope/pimp-my-box/blob/master/roles/pyenv/files/pyenv.sh
i have been trying different things, but I can't get it to stop complaining. 

i tried  `export PYENV_DEBUG=1` and i get the following:
```
+ [pyenv-sh-activate:90] new_venv=2.7.13/envs/--no-error
+ [pyenv-sh-activate:91] pyenv-virtualenv-prefix 2.7.13/envs/--no-error
+ [pyenv-sh-activate:95] '[' -z '' ']'
+ [pyenv-sh-activate:96] echo 'pyenv-virtualenv: version `--no-error'\'' is not a virtualenv'
pyenv-virtualenv: version `--no-error' is not a virtualenv
+ [pyenv-sh-activate:98] echo false
+ [pyenv-sh-activate:99] exit 1
```

does that shed any light?

**Comment by 2600box** [comment]
ok, i've been looking at these logs some more.

```
++ [pyenv:120] command -v pyenv-sh-activate
+ [pyenv:120] command_path=/home/rtorrent/.local/pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate
+ [pyenv:121] '[' -n /home/rtorrent/.local/pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate ']'
+ [pyenv:123] shift 1
+ [pyenv:124] '[' --no-error = --help ']'
+ [pyenv:131] exec /home/rtorrent/.local/pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate --no-error --verbose
+ [pyenv-sh-activate:17] '[' -z /home/rtorrent/.local/pyenv ']'
+ [pyenv-sh-activate:25] unset FORCE
+ [pyenv-sh-activate:26] unset QUIET
+ [pyenv-sh-activate:28] '[' 2 -gt 0 ']'
+ [pyenv-sh-activate:29] case "$1" in
+ [pyenv-sh-activate:49] break
+ [pyenv-sh-activate:55] no_shell=
+ [pyenv-sh-activate:56] versions=("$@")
+ [pyenv-sh-activate:57] '[' -z --no-error ']'
+ [pyenv-sh-activate:64] '[' -z 1 ']'
+ [pyenv-sh-activate:70] venv=--no-error
+ [pyenv-sh-activate:72] '[' -n '' ']'
+ [pyenv-sh-activate:85] pyenv-virtualenv-prefix --no-error
+ [pyenv-sh-activate:87] OLDIFS=' 	
```
leads me to https://github.com/pyenv/pyenv-virtualenv/blob/master/bin/pyenv-sh-activate
if i run `/home/rtorrent/.local/pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate --no-error --verbose` I get an error `line 88: pyenv-version-name: command not found`

this file does exist here: `./.local/pyenv/libexec/pyenv-version-name`

should libexec be in my `$PATH` or is there something missing in the script?

**Comment by pyroscope** [comment]
One possible cause might be that that the file changed in pyenv itself, and doesn't fit anymore.

What shell did you use for those tests?

**Comment by 2600box** [comment]
using bash shell from rtorrent account. 

i have checked with diff that the pyenv-sh-activate and pyenv.sh do match those on github.
pyenv.sh is from august 2015. pyenv-sh-activate has had active development through 2015 and 2016...

**Comment by pyroscope** [comment]
See also #14, which will either uncover this, or show what's missing on your end.
