### ISSUE TITLE
 Support for Ubuntu Bionic

### ISSUE THREAD

**Issue by pyroscope** [pyroscope/pimp-my-box#25]
* New package names / missing packages
* Depends on #24, #23 and #22

**Comment by Gerald6494** [comment]
Sorry I'm new at this and I need some help to know what to do next. pimp-my-box was installing when I Remove the lines for libav from within the main.yml file located in the common/task folder, but now it is stuck again look below. I had made a new post of this but it was closed and someone left a comment  "dupe" I don't know what suppose to mean. I just need help to get pimp-my-box working with no errors. Thanks

TASK [rutorrent : Load distro-specific variables] **********************************************************************
ok: [my-box] => (item=/home/remote/src/pimp-my-box/roles/rutorrent/vars/os_default.yml)

TASK [rutorrent : Create rutorrent group] ******************************************************************************
changed: [my-box]

TASK [rutorrent : Create rutorrent user] *******************************************************************************
changed: [my-box]

TASK [rutorrent : Add rtorrent user to www-data group] *****************************************************************
changed: [my-box]

TASK [rutorrent : Create rutorrent home directories] *******************************************************************
changed: [my-box] => (item=.)
changed: [my-box] => (item=bin)
changed: [my-box] => (item=src)
changed: [my-box] => (item=profile)
changed: [my-box] => (item=profile/users)
changed: [my-box] => (item=profile/settings)
changed: [my-box] => (item=profile/torrents)

TASK [rutorrent : Install PHP packages] ********************************************************************************
**failed: [my-box] (item=[u'php5-cli', u'php5-fpm', u'php-apc']) => {"changed": false, "item": ["php5-cli", "php5-fpm", "php-apc"], "msg": "No package matching 'php5-cli' is available"}**
to retry, use: --limit @/home/remote/src/pimp-my-box/site.retry

PLAY RECAP *************************************************************************************************************
my-box : ok=60 changed=44 unreachable=0 failed=1

**Comment by pyroscope** [comment]
You have to wait till I get the time to change things, which is *not* a simple fix. Alternatives are in the Google group.

**Comment by Gerald6494** [comment]
Ok, Thanks for your reply. I will wait until you're ready to fix it. I was in Google group and I did get some help for "realpath" was not working, but the admin told me to come here for the support for Ubuntu Bionic.  Thanks Again.

**Comment by pyroscope** [comment]
Works, without ruTorrent.

**Comment by Gerald6494** [comment]
Thanks for the update. I ran this command "**sudo git pull --ff-only**" and it did do a lot of updates, but I;m still getting the error below when it was installing the packages.  Please tell me how I can fix it and remove ruTorrent from the package or when will it be fixed. Thank You

 
TASK [nginx : Render index HTML + CSS] *********************************************************************************
ok: [my-box] => (item=index.html)
ok: [my-box] => (item=50x.html)
ok: [my-box] => (item=css/default.css)

TASK [rutorrent : Load distro-specific variables] **********************************************************************
ok: [my-box] => (item=/home/remote/src/pimp-my-box/roles/rutorrent/vars/os_default.yml)

TASK [rutorrent : Create rutorrent group] ******************************************************************************
ok: [my-box]

TASK [rutorrent : Create rutorrent user] *******************************************************************************
ok: [my-box]

TASK [rutorrent : Add rtorrent user to www-data group] *****************************************************************
ok: [my-box]

TASK [rutorrent : Create rutorrent home directories] *******************************************************************
ok: [my-box] => (item=.)
ok: [my-box] => (item=bin)
ok: [my-box] => (item=src)
ok: [my-box] => (item=profile)
ok: [my-box] => (item=profile/users)
ok: [my-box] => (item=profile/settings)
ok: [my-box] => (item=profile/torrents)

TASK [rutorrent : Install PHP packages] ********************************************************************************
**failed: [my-box] (item=[u'php5-cli', u'php5-fpm', u'php-apc']) => {"changed": false, "item": ["php5-cli", "php5-fpm", "php-apc"], "msg": "No package matching 'php5-cli' is available"}
        to retry, use: --limit @/home/remote/src/pimp-my-box/site.retry**

PLAY RECAP *************************************************************************************************************
my-box                     : ok=68   changed=1    unreachable=0    failed=1

**Comment by pyroscope** [comment]
Remaining changes will be done in #23.
