### ISSUE TITLE
Support for Ubuntu Bionic

### ISSUE THREAD

**Issue by Gerald6494** [pyroscope/pimp-my-box#27]
It was installing when I Remove the lines for **libav** from within the **main.yml** file located in the **common/task** folder, but now it is stuck again look below.

TASK [rutorrent : Load distro-specific variables] **********************************************************************
ok: [my-box] => (item=/home/remote/src/pimp-my-box/roles/rutorrent/vars/os_default.yml)

TASK [rutorrent : Create rutorrent group] ******************************************************************************
changed: [my-box]

TASK [rutorrent : Create rutorrent user] *******************************************************************************
changed: [my-box]

TASK [rutorrent : Add rtorrent user to www-data group] *****************************************************************
changed: [my-box]

TASK [rutorrent : Create rutorrent home directories] *******************************************************************
changed: [my-box] => (item=.)
changed: [my-box] => (item=bin)
changed: [my-box] => (item=src)
changed: [my-box] => (item=profile)
changed: [my-box] => (item=profile/users)
changed: [my-box] => (item=profile/settings)
changed: [my-box] => (item=profile/torrents)

TASK [rutorrent : Install PHP packages] ********************************************************************************
**failed: [my-box] (item=[u'php5-cli', u'php5-fpm', u'php-apc']) => {"changed": false, "item": ["php5-cli", "php5-fpm", "php-apc"], "msg": "No package matching 'php5-cli' is available"}**
        to retry, use: --limit @/home/remote/src/pimp-my-box/site.retry

PLAY RECAP *************************************************************************************************************
my-box                     : ok=60   changed=44   unreachable=0    failed=1

**Comment by pyroscope** [comment]
dupe.
