### ISSUE TITLE
Starting rTorrent on Target Error

### ISSUE THREAD

**Issue by Omniusol** [pyroscope/pimp-my-box#30]
Followed the guide and all is well. I log into the target server with the rtorrent user **setup** 
I run the command `tmux -2u new -n rT-PS -s rtorrent "~/rtorrent/start; exec bash"`
I seems to open a tmux session with a caveat it says 'bash: /home/setup/rtorrent/start: No such file or directory'
I checked and all the rtorrent stuff is in /home/rtorrent is that correct?

**Comment by pyroscope** [comment]
“So to start rTorrent, **log in as the rtorrent user** and start this command”

The rtorrent user is the user named "rtorrent".
