### ISSUE TITLE
missing programs as part of the initial install

### ISSUE THREAD

**Issue by tombs007** [pyroscope/pimp-my-box#4]
Debian Jessie

screenshots: Plugin will not work. rTorrent user can't access external program (ffmpeg).
Installed from source. https://www.assetbank.co.uk/support/documentation/install/ffmpeg-debian-squeeze/ffmpeg-debian-jessie/

mediainfo: Plugin will not work. rTorrent user can't access external program (mediainfo).
apt-get install mediainfo

Unpack plugin: rTorrent user can't access 'unrar' program.
apt-get install unrar-free

**Comment by pyroscope** [comment]
Regarding ffmpeg, open an issue with ruTorrent to also handle libav (avconv), or else use Debian instead of Ubuntu.
